// AI 교육 탭의 강의 시드 목록 — AI 랭킹의 ai-tools.ts 와 같은 "직접 큐레이션" 방식.
//  - 저장하는 건 메타데이터(제목·플랫폼·링크·카테고리·태그)뿐. 강의 본문/커리큘럼은 복제하지 않고
//    카드 클릭 시 원본으로 링크아웃(target="_blank")한다. 뉴스 큐레이션과 동일한 안전 범위.
//  - URL 은 웹 검색으로 실재를 확인한 것만 넣는다(지어내지 않는다).
//  - 신규 강의는 이 배열에 한 줄 추가하면 됨. 추후 스크래핑/제휴 API 로 자동화 여지.

export type CourseCategoryKey = "intro" | "llm" | "media" | "data" | "practice";

export const COURSE_CATEGORIES: { key: CourseCategoryKey | "all"; label: string }[] = [
  { key: "all", label: "전체" },
  { key: "intro", label: "입문" },
  { key: "llm", label: "LLM·에이전트" },
  { key: "media", label: "이미지·영상" },
  { key: "data", label: "데이터·ML" },
  { key: "practice", label: "실무·활용" },
];

export type Course = {
  title: string;
  platform: string; // 표기 그대로(배지 색은 PLATFORM_BADGE 에서 매핑, 없으면 중립색)
  url: string;
  category: CourseCategoryKey;
  level: "입문" | "중급" | "고급";
  free: boolean; // 유튜브·공개강의 등 무료면 true → '무료' 배지/필터
  tags: string[];
};

export const COURSES: Course[] = [
  // ── 입문 ──────────────────────────────────────────────
  {
    title: "Claude Code 왕초보 입문 튜토리얼 (23가지 팁·50분)",
    platform: "유튜브",
    url: "https://www.youtube.com/watch?v=1_bRmkUvjHA",
    category: "intro",
    level: "입문",
    free: true,
    tags: ["클로드코드", "입문"],
  },
  {
    title: "ChatGPT 101 : 직장인·크리에이터·비즈니스 활용법",
    platform: "클래스101",
    url: "https://class101.net/en/products/64584bb3fa7e16007638db72",
    category: "intro",
    level: "입문",
    free: false,
    tags: ["ChatGPT", "직장인"],
  },
  {
    title: "조코딩 JoCoding — 코딩·AI 입문 채널",
    platform: "유튜브",
    url: "https://www.youtube.com/@jocoding",
    category: "intro",
    level: "입문",
    free: true,
    tags: ["코딩", "수익화", "노코드"],
  },

  // ── LLM·에이전트 ──────────────────────────────────────
  {
    title: "ChatGPT Prompt Engineering for Developers (Isa Fulford · Andrew Ng)",
    platform: "deeplearning.ai",
    url: "https://www.deeplearning.ai/short-courses/chatgpt-prompt-engineering-for-developers",
    category: "llm",
    level: "입문",
    free: true,
    tags: ["프롬프트", "ChatGPT", "OpenAI", "Andrew Ng", "영어"],
  },
  {
    title: "AI Agents in LangGraph (Harrison Chase · Rotem Weiss)",
    platform: "deeplearning.ai",
    url: "https://www.deeplearning.ai/courses/ai-agents-in-langgraph",
    category: "llm",
    level: "중급",
    free: true,
    tags: ["LangGraph", "에이전트", "LangChain", "Tavily", "영어"],
  },
  {
    title: "AI Agent + MCP 초자동화로 앞서나가기",
    platform: "코딩애플",
    url: "https://codingapple.com/course/ai-agent-mcp/",
    category: "llm",
    level: "입문",
    free: false,
    tags: ["AI에이전트", "MCP", "자동화", "노코드"],
  },
  {
    title: "Agentic AI — 에이전트 설계 4대 패턴 (Andrew Ng)",
    platform: "deeplearning.ai",
    url: "https://www.deeplearning.ai/courses/agentic-ai/",
    category: "llm",
    level: "중급",
    free: true,
    tags: ["에이전트", "멀티에이전트", "Andrew Ng", "영어"],
  },
  {
    title: "MCP로 엔터프라이즈 환경에서 AI Agent 활용 및 제어",
    platform: "패스트캠퍼스",
    url: "https://fastcampus.co.kr/data_online_mcp",
    category: "llm",
    level: "중급",
    free: false,
    tags: ["MCP", "에이전트", "엔터프라이즈"],
  },
  {
    title: "LangGraph를 활용한 LLM Agent 개발 강의 (feat. MCP)",
    platform: "인프런",
    url: "https://www.inflearn.com/course/%EB%9E%AD%EA%B7%B8%EB%9E%98%ED%94%84-%ED%99%9C%EC%9A%A9%ED%95%9C-llm%EC%97%90%EC%9D%B4%EC%A0%84%ED%8A%B8-%EA%B0%9C%EB%B0%9C",
    category: "llm",
    level: "중급",
    free: false,
    tags: ["LangGraph", "에이전트", "MCP"],
  },

  {
    title: "최고의 프롬프트 엔지니어링 (ft. 바이브 코딩)",
    platform: "패스트캠퍼스",
    url: "https://fastcampus.co.kr/data_red_golbin",
    category: "llm",
    level: "중급",
    free: false,
    tags: ["프롬프트", "바이브코딩"],
  },
  {
    title: "AI 에이전트로 구현하는 RAG 시스템 (w. LangGraph)",
    platform: "인프런",
    url: "https://www.inflearn.com/course/ai%EC%97%90%EC%9D%B4%EC%A0%84%ED%8A%B8-%EA%B5%AC%ED%98%84-rag%EC%8B%9C%EC%8A%A4%ED%85%9C-%EB%9E%AD%EA%B7%B8%EB%9E%98%ED%94%84",
    category: "llm",
    level: "고급",
    free: false,
    tags: ["RAG", "LangGraph", "에이전트"],
  },
  {
    title: "노마드코더 — AI 비서·멀티 에이전트·자동화",
    platform: "유튜브",
    url: "https://www.youtube.com/@nomadcoders",
    category: "llm",
    level: "중급",
    free: true,
    tags: ["에이전트", "자동화"],
  },
  {
    title: "Claude의 모든 것 : Cowork·Code·Skills 200% 활용 (자동화·에이전트)",
    platform: "패스트캠퍼스",
    url: "https://fastcampus.co.kr/biz_online_claude",
    category: "llm",
    level: "중급",
    free: false,
    tags: ["클로드", "Claude Code", "자동화"],
  },
  {
    title: "Anthropic Academy — Claude·Claude Code·MCP 공식 강좌",
    platform: "Anthropic",
    url: "https://anthropic.skilljar.com/",
    category: "llm",
    level: "입문",
    free: true,
    tags: ["클로드", "Claude Code", "MCP", "영어"],
  },
  {
    title: "클로드 코드 완벽 마스터: AI 개발 워크플로우 기초부터 실전까지",
    platform: "인프런",
    url: "https://www.inflearn.com/course/%ED%81%B4%EB%A1%9C%EB%93%9C-%EC%BD%94%EB%93%9C-%EC%99%84%EB%B2%BD-%EB%A7%88%EC%8A%A4%ED%84%B0-ai-%EA%B0%9C%EB%B0%9C",
    category: "llm",
    level: "중급",
    free: false,
    tags: ["클로드코드", "Claude Code", "MCP", "에이전트"],
  },
  {
    title: "클로드 코드 강의 모음전 (무료·유료)",
    platform: "인프런",
    url: "https://www.inflearn.com/pages/claudecode2026",
    category: "llm",
    level: "입문",
    free: false,
    tags: ["클로드코드", "강의모음"],
  },
  {
    title: "테디노트 TeddyNote — LangChain·RAG 한국어 채널",
    platform: "유튜브",
    url: "https://www.youtube.com/channel/UCt2wAAXgm87ACiQnDHQEW6Q",
    category: "llm",
    level: "중급",
    free: true,
    tags: ["LangChain", "RAG", "딥러닝"],
  },
  {
    title: "테디노트의 RAG 비법노트: 랭체인 기반의 GPT·로컬 모델부터 LangGraph·Agent까지",
    platform: "패스트캠퍼스",
    url: "https://fastcampus.co.kr/data_online_teddy",
    category: "llm",
    level: "고급",
    free: false,
    tags: ["LangChain", "RAG", "LangGraph", "에이전트"],
  },
  {
    title: "Claude Code × Codex로 10배 똑똑한 AI Agent 팀 구축부터 운영까지",
    platform: "패스트캠퍼스",
    url: "https://fastcampus.co.kr/biz_online_claudecodex",
    category: "llm",
    level: "고급",
    free: false,
    tags: ["클로드코드", "Claude Code", "Codex", "에이전트"],
  },
  {
    title: "MCP와 A2A로 끝내는 상상도 못할 Multi-Agent 구축",
    platform: "패스트캠퍼스",
    url: "https://fastcampus.co.kr/data_online_mcpa2a",
    category: "llm",
    level: "중급",
    free: false,
    tags: ["MCP", "A2A", "멀티에이전트", "LangGraph"],
  },
  {
    title: "AI Agent 바이블: n8n부터 LangGraph까지, 멀티 에이전트의 모든 것",
    platform: "패스트캠퍼스",
    url: "https://fastcampus.co.kr/data_online_aiagentbible",
    category: "llm",
    level: "고급",
    free: false,
    tags: ["n8n", "LangGraph", "OpenAI", "멀티에이전트", "RAG", "에이전트"],
  },

  // ── 이미지·영상 ───────────────────────────────────────
  {
    title: "AI로 완성하는 5가지 감도높은 광고 제작: 이미지·음악·영상·편집까지",
    platform: "패스트캠퍼스",
    url: "https://fastcampus.co.kr/dgn_online_aiads",
    category: "media",
    level: "중급",
    free: false,
    tags: ["AI광고", "AI영상", "이미지생성", "음악생성", "콘텐츠"],
  },
  {
    title: "일관성을 유지하는 AI 영상 제작 with Midjourney & Runway",
    platform: "패스트캠퍼스",
    url: "https://fastcampus.co.kr/data_online_keepkwan",
    category: "media",
    level: "입문",
    free: false,
    tags: ["미드저니", "Runway", "AI영상", "숏폼", "스토리보드"],
  },
  {
    title: "왕초보를 위한 AI 디자인 바이블 (MJ·SD·Firefly)",
    platform: "패스트캠퍼스",
    url: "https://fastcampus.co.kr/data_online_aibeginner",
    category: "media",
    level: "입문",
    free: false,
    tags: ["미드저니", "Stable Diffusion", "디자인"],
  },
  {
    title: "미드저니·SD로 만드는 하이퀄리티 이미지&영상",
    platform: "패스트캠퍼스",
    url: "https://fastcampus.co.kr/data_online_qualityai",
    category: "media",
    level: "중급",
    free: false,
    tags: ["미드저니", "Stable Diffusion", "영상"],
  },
  {
    title: "Stable Diffusion 필독 가이드 (WebUI 세팅부터)",
    platform: "패스트캠퍼스",
    url: "https://fastcampus.co.kr/media_data_sd",
    category: "media",
    level: "중급",
    free: false,
    tags: ["Stable Diffusion", "WebUI"],
  },
  {
    title: "생성형 AI 입문 7시간 완성 (Stable Diffusion)",
    platform: "유튜브",
    url: "https://www.youtube.com/watch?v=AS7uB1R9Z0s",
    category: "media",
    level: "입문",
    free: true,
    tags: ["Stable Diffusion", "이미지", "영상"],
  },
  {
    title: "2026 AI 영상 마스터클래스: 광고·콘텐츠·숏폼까지 무한 확장",
    platform: "패스트캠퍼스",
    url: "https://fastcampus.co.kr/dgn_online_aiall",
    category: "media",
    level: "중급",
    free: false,
    tags: ["AI영상", "광고", "숏폼", "콘텐츠"],
  },

  // ── 데이터·ML ────────────────────────────────────────
  {
    title: "Practical Deep Learning for Coders (Jeremy Howard / fast.ai)",
    platform: "fast.ai",
    url: "https://course.fast.ai/",
    category: "data",
    level: "입문",
    free: true,
    tags: ["딥러닝", "PyTorch", "fastai", "영어", "Kaggle"],
  },
  {
    title: "혼자 공부하는 머신러닝+딥러닝 (박해선)",
    platform: "인프런",
    url: "https://www.inflearn.com/course/%ED%98%BC%EC%9E%90%EA%B3%B5%EB%B6%80-%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D-%EB%94%A5%EB%9F%AC%EB%8B%9D",
    category: "data",
    level: "입문",
    free: true,
    tags: ["머신러닝", "딥러닝", "기초", "scikit-learn"],
  },
  {
    title: "모두를 위한 머신러닝/딥러닝 (김성훈)",
    platform: "공개강의",
    url: "https://hunkim.github.io/ml/",
    category: "data",
    level: "입문",
    free: true,
    tags: ["머신러닝", "딥러닝", "기초"],
  },
  {
    title: "혁펜하임 — Easy! 딥러닝·머신러닝 강의 채널 (KAIST PhD)",
    platform: "유튜브",
    url: "https://www.youtube.com/@hyukppen",
    category: "data",
    level: "입문",
    free: true,
    tags: ["딥러닝", "머신러닝", "기초"],
  },
  {
    title: "DeepLearning.AI Short Courses (Andrew Ng)",
    platform: "deeplearning.ai",
    url: "https://www.deeplearning.ai/courses",
    category: "data",
    level: "중급",
    free: true,
    tags: ["딥러닝", "Andrew Ng", "영어"],
  },

  // ── 실무·활용 ────────────────────────────────────────
  {
    title: "실리콘밸리 바이브코딩: 상위 1% 개발자의 10가지 스킬 with Claude Code & Codex",
    platform: "패스트캠퍼스",
    url: "https://fastcampus.co.kr/data_online_svvibecoding",
    category: "practice",
    level: "고급",
    free: false,
    tags: ["바이브코딩", "Claude Code", "Codex", "SaaS", "풀스택"],
  },
  {
    title: "코딩 없이 AI 자동화 전문가가 되는 법, n8n 완벽 가이드",
    platform: "인프런",
    url: "https://www.inflearn.com/course/ai-%EC%9E%90%EB%8F%99%ED%99%94-n8n",
    category: "practice",
    level: "입문",
    free: false,
    tags: ["n8n", "자동화", "노코드", "워크플로우", "AI에이전트"],
  },
  {
    title: "일잘러를 위한 700가지 ChatGPT 활용 바이블",
    platform: "패스트캠퍼스",
    url: "https://fastcampus.co.kr/biz_online_chatgpt700",
    category: "practice",
    level: "입문",
    free: false,
    tags: ["ChatGPT", "업무자동화"],
  },
  {
    title: "1일 1바이브코딩 30개 프로젝트 완성: Cursor AI × Claude Code로 돈 버는 웹&앱 만들기",
    platform: "패스트캠퍼스",
    url: "https://fastcampus.co.kr/biz_online_vibecoding30",
    category: "practice",
    level: "입문",
    free: false,
    tags: ["바이브코딩", "Cursor AI", "Claude Code", "수익화"],
  },
];
