import type { Article } from "./types";

const hoursAgo = (h: number) => new Date(Date.now() - h * 3600 * 1000).toISOString();

export const MOCK_ARTICLES: Article[] = [
  {
    id: "1",
    title: "Claude Opus 4.7 release notes: longer context, sharper tool use",
    url: "https://www.anthropic.com/news/claude-opus-4-7",
    source: "Anthropic",
    category: "LLM",
    summary: "1M-context Opus, improved agentic benchmarks, and new tool-use evals.",
    thumbnail_url: "https://placehold.co/640x360/0f172a/e2e8f0?text=Claude+4.7",
    published_at: hoursAgo(2),
    likes_count: 142,
  },
  {
    id: "2",
    title: "GPT-5o public benchmarks leaked ahead of release",
    url: "https://techcrunch.com/2026/06/gpt5o-leak",
    source: "TechCrunch",
    category: "LLM",
    summary: "Internal eval table surfaces on a public CDN; OpenAI declines comment.",
    thumbnail_url: "https://placehold.co/640x360/1e293b/f1f5f9?text=GPT-5o",
    published_at: hoursAgo(5),
    likes_count: 87,
  },
  {
    id: "3",
    title: "Mixture-of-Depths: dynamic compute allocation for transformers",
    url: "https://arxiv.org/abs/2606.12345",
    source: "arXiv",
    category: "LLM",
    summary: "Layer-wise routing reduces FLOPs 35% while matching dense baselines.",
    thumbnail_url: "https://placehold.co/640x360/064e3b/d1fae5?text=MoD+Paper",
    published_at: hoursAgo(8),
    likes_count: 56,
  },
  {
    id: "4",
    title: "프로덕션 RAG 파이프라인을 처음부터 구축한 6개월의 기록",
    url: "https://news.hada.io/topic?id=rag-in-production",
    source: "GeekNews",
    category: "Practice",
    summary: "벡터 DB 선택부터 재순위(reranking), 평가 자동화까지 — 실전에서 배운 것들.",
    thumbnail_url: "https://placehold.co/640x360/78350f/fef3c7?text=RAG+in+Prod",
    published_at: hoursAgo(12),
    likes_count: 213,
  },
  {
    id: "5",
    title: "Gemini 3 Vision: native 4K image reasoning at 90 FPS",
    url: "https://blog.google/technology/ai/gemini-3-vision",
    source: "Google AI",
    category: "LLM",
    summary: "Streaming visual reasoning surpasses GPT-4o-V on MMMU and VideoBench.",
    thumbnail_url: "https://placehold.co/640x360/075985/cffafe?text=Gemini+3+Vision",
    published_at: hoursAgo(18),
    likes_count: 98,
  },
  {
    id: "6",
    title: "Meta open-sources Llama 4 70B with full training recipe",
    url: "https://ai.meta.com/blog/llama-4-70b-release",
    source: "Meta AI",
    category: "LLM",
    summary: "Apache 2.0, includes dataset cards, RM weights, and eval harness configs.",
    thumbnail_url: "https://placehold.co/640x360/581c87/f3e8ff?text=Llama+4",
    published_at: hoursAgo(22),
    likes_count: 304,
  },
  {
    id: "7",
    title: "MCP 서버 직접 만들어 사내 도구를 Claude에 연결한 사례",
    url: "https://yozm.wishket.com/magazine/detail/mcp-server",
    source: "요즘IT",
    category: "Practice",
    summary: "Model Context Protocol로 내부 위키·이슈 트래커를 에이전트에 붙인 실전 가이드.",
    thumbnail_url: "https://placehold.co/640x360/881337/ffe4e6?text=MCP+Server",
    published_at: hoursAgo(28),
    likes_count: 412,
  },
  {
    id: "8",
    title: "Anthropic publishes mechanistic interpretability roadmap to 2028",
    url: "https://www.anthropic.com/research/mech-interp-roadmap",
    source: "Anthropic",
    category: "LLM",
    summary: "Three pillars: feature dictionaries, circuit-level safety audits, ablations.",
    thumbnail_url: "https://placehold.co/640x360/0c4a6e/e0f2fe?text=Mech+Interp",
    published_at: hoursAgo(34),
    likes_count: 178,
  },
  {
    id: "9",
    title: "Cursor vs Claude Code: 실무 팀이 둘 다 쓰는 이유",
    url: "https://techcrunch.com/2026/06/cursor-vs-claude-code",
    source: "TechCrunch",
    category: "Tools",
    summary: "라인 단위 편집은 Cursor, 목표 단위 위임은 Claude Code — 2026년의 표준 조합.",
    thumbnail_url: "https://placehold.co/640x360/3f3f46/fafafa?text=Cursor+vs+CC",
    published_at: hoursAgo(40),
    likes_count: 64,
  },
  {
    id: "10",
    title: "OpenAI Codex ships browser-driving agent SDK preview",
    url: "https://openai.com/blog/codex-agent-sdk",
    source: "OpenAI",
    category: "Tools",
    summary: "Headless Chromium under the hood, with new ARIA-aware action grammar.",
    thumbnail_url: "https://placehold.co/640x360/1e3a8a/dbeafe?text=Codex+SDK",
    published_at: hoursAgo(46),
    likes_count: 121,
  },
  {
    id: "11",
    title: "신입 개발자 채용 비중 53%→37%… AI가 바꾸는 IT 채용 시장",
    url: "https://www.etnews.com/2026/ai-hiring-shift",
    source: "전자신문",
    category: "LLM",
    summary: "3년 미만 신입은 줄고 3년 이상 경력자 수요는 급증. 요구 역량도 'AI 협업'으로 이동.",
    thumbnail_url: "https://placehold.co/640x360/065f46/d1fae5?text=AI+Hiring",
    published_at: hoursAgo(55),
    likes_count: 256,
  },
  {
    id: "12",
    title: "LangGraph로 멀티 에이전트 워크플로우를 실제 서비스에 올린 후기",
    url: "https://news.hada.io/topic?id=langgraph-multiagent",
    source: "GeekNews",
    category: "Practice",
    summary: "상태 관리, 휴먼 인 더 루프, 비용 통제까지 — 프로토타입과 프로덕션의 간극.",
    thumbnail_url: "https://placehold.co/640x360/9a3412/ffedd5?text=LangGraph",
    published_at: hoursAgo(62),
    likes_count: 189,
  },
];
