import type { Article } from "./types";

const hoursAgo = (h: number) => new Date(Date.now() - h * 3600 * 1000).toISOString();

export const MOCK_ARTICLES: Article[] = [
  {
    id: "1",
    title: "Claude Opus 4.7 release notes: longer context, sharper tool use",
    url: "https://www.anthropic.com/news/claude-opus-4-7",
    source: "Anthropic",
    category: "LLM",
    summary: "1M-context Opus, improved agentic benchmarks, and new tool-use evals.",
    thumbnail_url: "https://placehold.co/640x360/0f172a/e2e8f0?text=Claude+4.7",
    published_at: hoursAgo(2),
    likes_count: 142,
  },
  {
    id: "2",
    title: "GPT-5o public benchmarks leaked ahead of release",
    url: "https://techcrunch.com/2026/06/gpt5o-leak",
    source: "TechCrunch",
    category: "LLM",
    summary: "Internal eval table surfaces on a public CDN; OpenAI declines comment.",
    thumbnail_url: "https://placehold.co/640x360/1e293b/f1f5f9?text=GPT-5o",
    published_at: hoursAgo(5),
    likes_count: 87,
  },
  {
    id: "3",
    title: "Mixture-of-Depths: dynamic compute allocation for transformers",
    url: "https://arxiv.org/abs/2606.12345",
    source: "arXiv",
    category: "Research",
    summary: "Layer-wise routing reduces FLOPs 35% while matching dense baselines.",
    thumbnail_url: "https://placehold.co/640x360/064e3b/d1fae5?text=MoD+Paper",
    published_at: hoursAgo(8),
    likes_count: 56,
  },
  {
    id: "4",
    title: "Figure 03 humanoid demos kitchen prep in 4 minutes flat",
    url: "https://www.theverge.com/2026/06/figure-03-demo",
    source: "The Verge",
    category: "Robotics",
    summary: "End-to-end VLA policy, no scripted motions, all on-device inference.",
    thumbnail_url: "https://placehold.co/640x360/78350f/fef3c7?text=Figure+03",
    published_at: hoursAgo(12),
    likes_count: 213,
  },
  {
    id: "5",
    title: "Gemini 3 Vision: native 4K image reasoning at 90 FPS",
    url: "https://blog.google/technology/ai/gemini-3-vision",
    source: "Google AI",
    category: "Vision",
    summary: "Streaming visual reasoning surpasses GPT-4o-V on MMMU and VideoBench.",
    thumbnail_url: "https://placehold.co/640x360/075985/cffafe?text=Gemini+3+Vision",
    published_at: hoursAgo(18),
    likes_count: 98,
  },
  {
    id: "6",
    title: "Meta open-sources Llama 4 70B with full training recipe",
    url: "https://ai.meta.com/blog/llama-4-70b-release",
    source: "Meta AI",
    category: "LLM",
    summary: "Apache 2.0, includes dataset cards, RM weights, and eval harness configs.",
    thumbnail_url: "https://placehold.co/640x360/581c87/f3e8ff?text=Llama+4",
    published_at: hoursAgo(22),
    likes_count: 304,
  },
  {
    id: "7",
    title: "Show HN: I built a local voice assistant on a Raspberry Pi 5",
    url: "https://news.ycombinator.com/item?id=99999991",
    source: "Hacker News",
    category: "Industry",
    summary: "Whisper-tiny + Llama-3.2-1B + Piper, sub-second latency on a $79 board.",
    thumbnail_url: "https://placehold.co/640x360/881337/ffe4e6?text=Show+HN",
    published_at: hoursAgo(28),
    likes_count: 412,
  },
  {
    id: "8",
    title: "Anthropic publishes mechanistic interpretability roadmap to 2028",
    url: "https://www.anthropic.com/research/mech-interp-roadmap",
    source: "Anthropic",
    category: "Research",
    summary: "Three pillars: feature dictionaries, circuit-level safety audits, ablations.",
    thumbnail_url: "https://placehold.co/640x360/0c4a6e/e0f2fe?text=Mech+Interp",
    published_at: hoursAgo(34),
    likes_count: 178,
  },
  {
    id: "9",
    title: "Cursor raises $300M Series D at $9B valuation",
    url: "https://techcrunch.com/2026/06/cursor-series-d",
    source: "TechCrunch",
    category: "Industry",
    summary: "Coatue leads round; ARR reportedly crossed $400M run-rate last month.",
    thumbnail_url: "https://placehold.co/640x360/3f3f46/fafafa?text=Cursor+%24300M",
    published_at: hoursAgo(40),
    likes_count: 64,
  },
  {
    id: "10",
    title: "OpenAI Operator-2 ships with browser agent SDK preview",
    url: "https://openai.com/blog/operator-2",
    source: "OpenAI",
    category: "Industry",
    summary: "Headless Chromium under the hood, with new ARIA-aware action grammar.",
    thumbnail_url: "https://placehold.co/640x360/1e3a8a/dbeafe?text=Operator+2",
    published_at: hoursAgo(46),
    likes_count: 121,
  },
  {
    id: "11",
    title: "DeepMind: training a 1T-parameter MoE on 10K H200s in 12 days",
    url: "https://deepmind.google/research/moe-training-1t",
    source: "Google AI",
    category: "Research",
    summary: "Sparse routing + memory-mapped optimizer states; full systems writeup.",
    thumbnail_url: "https://placehold.co/640x360/065f46/d1fae5?text=1T+MoE",
    published_at: hoursAgo(55),
    likes_count: 256,
  },
  {
    id: "12",
    title: "Boston Dynamics + Toyota: Atlas now folds laundry end-to-end",
    url: "https://www.wired.com/story/atlas-laundry-toyota",
    source: "Wired",
    category: "Robotics",
    summary: "VLA policy fine-tuned on 200h of teleoperation, no task-specific code.",
    thumbnail_url: "https://placehold.co/640x360/9a3412/ffedd5?text=Atlas+Laundry",
    published_at: hoursAgo(62),
    likes_count: 189,
  },
];
